version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - escom-network

  backend:
    build:
      context: ../BackenTT/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - escom-network

networks:
  escom-network:
    driver: bridge