version: '3.8'

services:
  frontend:
    build: 
      context: ./FrontendESCOMmed
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - escom-network

  backend:
    image: your-backend-image:latest # Reemplaza con tu imagen del backend
    ports:
      - "8080:8080"
    networks:
      - escom-network

networks:
  escom-network:
    driver: bridge