# Versión compatible con Docker Compose 1.27.0+
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - escom-network

  backend:
    image: your-backend-image:latest
    ports:
      - "8080:8080"
    networks:
      - escom-network

networks:
  escom-network:
    driver: bridge